Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  post 'perfumes/question1' => 'perfumes#question1'
  get 'perfumes/question2' => 'perfumes#question2'
  get 'perfumes/question3' => 'perfumes#question3'
  get 'perfumes/question4' => 'perfumes#question4'
  get 'perfumes/question5' => 'perfumes#question5'
  get 'perfumes/question6' => 'perfumes#question6'
  get 'perfumes/question7' => 'perfumes#question7'
  get 'perfumes/question8' => 'perfumes#question8'
  get 'perfumes/question9' => 'perfumes#question9'
  get 'perfumes/question10' => 'perfumes#question10'
  get 'perfumes/question11' => 'perfumes#question11'
  get 'perfumes/question12' => 'perfumes#question12'
  get 'perfumes/question13' => 'perfumes#question13'
  get 'perfumes/question14' => 'perfumes#question14'
  get 'perfumes/question15' => 'perfumes#question15'
  get 'perfumes/question16' => 'perfumes#question16'
  get 'perfumes/question17' => 'perfumes#question17'
  get 'perfumes/question18' => 'perfumes#question18'
  get 'perfumes/question19' => 'perfumes#question19'
  get 'perfumes/question20' => 'perfumes#question20'
  get 'perfumes/question21' => 'perfumes#question21'
  get 'perfumes/question22' => 'perfumes#question22'
  get 'perfumes/question23' => 'perfumes#question23'
  get 'perfumes/question24' => 'perfumes#question24'
  get 'perfumes/question25' => 'perfumes#question25'
  get 'perfumes/question26' => 'perfumes#question26'
  get 'perfumes/question27' => 'perfumes#question27'
  get 'perfumes/question28' => 'perfumes#question28'
  get 'perfumes/question29' => 'perfumes#question29'
  get 'perfumes/question30' => 'perfumes#question30'
  get 'perfumes/question31' => 'perfumes#question31'
  get 'perfumes/question32' => 'perfumes#question32'
  get 'perfumes/question33' => 'perfumes#question33'
  get 'perfumes/question34' => 'perfumes#question34'
  get 'perfumes/question35' => 'perfumes#question35'
  get 'perfumes/question36' => 'perfumes#question36'
  get 'perfumes/question37' => 'perfumes#question37'
  get 'perfumes/question38' => 'perfumes#question38'
  get 'perfumes/question39' => 'perfumes#question39'
  get 'perfumes/question40' => 'perfumes#question40'
  get 'perfumes/question41' => 'perfumes#question41'
  get 'perfumes/question42' => 'perfumes#question42'
  get 'perfumes/question43' => 'perfumes#question43'
  get 'perfumes/question44' => 'perfumes#question44'
  get 'perfumes/question45' => 'perfumes#question45'
  get 'perfumes/question46' => 'perfumes#question46'
  get 'perfumes/question47' => 'perfumes#question47'

  get 'perfumes/show1' => 'perfumes#show1'
  get 'perfumes/show2' => 'perfumes#show2'
  get 'perfumes/show3' => 'perfumes#show3'
  get 'perfumes/show4' => 'perfumes#show4'
  get 'perfumes/show5' => 'perfumes#show5'
  get 'perfumes/show6' => 'perfumes#show6'
  get 'perfumes/show7' => 'perfumes#show7'
  get 'perfumes/show8' => 'perfumes#show8'
  get 'perfumes/show9' => 'perfumes#show9'
  get 'perfumes/show10' => 'perfumes#show10'
  get 'perfumes/show11' => 'perfumes#show11'
  get 'perfumes/show12' => 'perfumes#show12'
  get 'perfumes/show13' => 'perfumes#show13'
  get 'perfumes/show14' => 'perfumes#show14'
  get 'perfumes/show15' => 'perfumes#show15'
  get 'perfumes/show16' => 'perfumes#show16'
  get 'perfumes/show17' => 'perfumes#show17'
  get 'perfumes/show18' => 'perfumes#show18'
  get 'perfumes/show19' => 'perfumes#show19'
  get 'perfumes/show20' => 'perfumes#show20'
  get 'perfumes/show21' => 'perfumes#show21'
  get 'perfumes/show22' => 'perfumes#show22'
  get 'perfumes/show23' => 'perfumes#show23'
  get 'perfumes/show24' => 'perfumes#show24'
  get 'perfumes/show25' => 'perfumes#show25'
  get 'perfumes/show26' => 'perfumes#show26'

  resources :perfumes
  resources :pens do
   resources :comments, only: [:create]
   end
  root 'pens#index'

end
